apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-depl
spec:
  select:
    matchLabels:
      app: postgre
    template:
      metadata:
        labels:
          app: postgre
      sepc:
        containers:
          - name: postgre
            image: postegrs:15.1
            ports:
            - containerPort: 5432
            env:
            - name: POSTGRE_DB
              value: "kubenews"
            - name: POSTGRE_USER
              value: "kubenews"
            - name: POSTGRE_PASSWORD
              value: "kube123"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre-serv
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
  type: ClusterIP
