apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre-depl
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:15.1
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: "kubenews"
          - name: POSTGRES_USER
            value: "kubenews"
          - name: POSTGRES_PASSWORD
            value: "kube123"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre-serv
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
  type: ClusterIP
